backend/afina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from lists.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('afina/', index, name='index'),
    path("afina/lists/", include("lists.urls", namespace="lists")),
    path("afina/finances/", include("finances.urls", namespace="finances")),
    path("", include("website.urls", namespace="website")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/finances/urls.py
from django.urls import path

from finances.views import wallets

app_name = "finances"

urlpatterns = [
    path('wallets/', wallets, name='wallets'),
]

backend/lists/urls.py
from django.urls import path

from lists.views import (
    index,
    MovieListView, MovieCreateView, MovieUpdateView, MovieDeleteView, MovieDetailView,
    GameListView, GameCreateView, GameDetailView, GameUpdateView, GameDeleteView,
    EventListView, EventCreateView, EventDetailView, EventUpdateView, EventDeleteView,
    IdeaListView, IdeaCreateView, IdeaDetailView, IdeaUpdateView, IdeaDeleteView,
    DesireListView, DesireCreateView, DesireDetailView, DesireUpdateView, DesireDeleteView,
    update_status,
)

app_name = "lists"

urlpatterns = [
    # region ---------- Movie Views  ----------
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/create/", MovieCreateView.as_view(), name="movie-create"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie-detail"),
    path("movies/<int:pk>/update/", MovieUpdateView.as_view(), name="movie-update"),
    path("movies/<int:pk>/delete/", MovieDeleteView.as_view(), name="movie-delete"),
    # endregion

    # region ---------- Game Views  ----------
    path("games/", GameListView.as_view(), name="game-list"),
    path("games/create/", GameCreateView.as_view(), name="game-create"),
    path("games/<int:pk>/", GameDetailView.as_view(), name="game-detail"),
    path("games/<int:pk>/update/", GameUpdateView.as_view(), name="game-update"),
    path("games/<int:pk>/delete/", GameDeleteView.as_view(), name="game-delete"),
    # endregion

    # region ---------- Game Views  ----------
    path("events/", EventListView.as_view(), name="event-list"),
    path("events/create/", EventCreateView.as_view(), name="event-create"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event-detail"),
    path("events/<int:pk>/update/", EventUpdateView.as_view(), name="event-update"),
    path("events/<int:pk>/delete/", EventDeleteView.as_view(), name="event-delete"),
    # endregion

    # region ---------- Idea Views  ----------
    path("ideas/", IdeaListView.as_view(), name="idea-list"),
    path("ideas/create/", IdeaCreateView.as_view(), name="idea-create"),
    path("ideas/<int:pk>/", IdeaDetailView.as_view(), name="idea-detail"),
    path("ideas/<int:pk>/update/", IdeaUpdateView.as_view(), name="idea-update"),
    path("ideas/<int:pk>/delete/", IdeaDeleteView.as_view(), name="idea-delete"),
    # idea

    # region ---------- Desire Views  ----------
    path("desires/", DesireListView.as_view(), name="desire-list"),
    path("desires/create/", DesireCreateView.as_view(), name="desire-create"),
    path("desires/<int:pk>/", DesireDetailView.as_view(), name="desire-detail"),
    path("desires/<int:pk>/update/", DesireUpdateView.as_view(), name="desire-update"),
    path("desires/<int:pk>/delete/", DesireDeleteView.as_view(), name="desire-delete"),
    path('<str:model_name>/<int:id>/update-status/', update_status, name='update-status'),
    # idea
]

backend/templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

backend/templates/includes/search_form.html
{% load crispy_forms_filters %}

<form method="get" action="" class="form-inline pb-2">
  <div class="form-group mb-2 w-25 d-inline-block">
    {{ search_form| crispy }}
  </div>
  <input type="submit" class="btn btn-secondary" value="🔍">
</form>

backend/templates/includes/sidebar.html
{% load static %}
<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
  <div class="d-flex align-items-center">
    <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
  <div class="sidebar-inner px-4 pt-3">
    <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
      <div class="collapse-close d-md-none">
        <a href="#sidebarMenu" data-bs-toggle="collapse"
           data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
           aria-label="Toggle navigation">
          <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd"></path>
          </svg>
        </a>
      </div>
    </div>
    <ul class="nav flex-column pt-3 pt-md-0">
      <li>
        <a href="{% url 'index' %}" class="nav-link d-flex align-items-center">
          <span class="sidebar-icon">
            <img alt="Afina" src="{% static 'assets/img/afina.png' %}" class="rounded-image">
          </span>
        </a>
      </li>
      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
      <li class="nav-item">
        <a href="{% url 'lists:movie-list' %}" class="nav-link">
          <span class="sidebar-text">Movies</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'lists:game-list' %}" class="nav-link">
          <span class="sidebar-text">Games</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'lists:event-list' %}" class="nav-link">
          <span class="sidebar-text">Events</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'lists:idea-list' %}" class="nav-link">
          <span class="sidebar-text">Ideas</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'lists:desire-list' %}" class="nav-link">
          <span class="sidebar-text">Desires</span>
        </a>
      </li>
      <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
      <li class="nav-item">
        <a href="{% url 'finances:wallets' %}" class="nav-link">
          <span class="sidebar-text">Wallets</span>
        </a>
      </li>
    </ul>
  </div>
</nav>