backend/afina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from lists.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('afina/', index, name='index'),
    path("afina/lists/", include("lists.urls", namespace="lists")),
    path("afina/finances/", include("finances.urls", namespace="finances")),
    path("", include("website.urls", namespace="website")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/lists/urls.py
from django.urls import path

from lists.views import (
    index,
    MovieListView, MovieCreateView, MovieUpdateView, MovieDeleteView, MovieDetailView,
    GameListView, GameCreateView, GameDetailView, GameUpdateView, GameDeleteView,
    EventListView, EventCreateView, EventDetailView, EventUpdateView, EventDeleteView,
    IdeaListView, IdeaCreateView, IdeaDetailView, IdeaUpdateView, IdeaDeleteView,
    DesireListView, DesireCreateView, DesireDetailView, DesireUpdateView, DesireDeleteView,
    update_status,
)

app_name = "lists"

urlpatterns = [
    # region ---------- Movie Views  ----------
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/create/", MovieCreateView.as_view(), name="movie-create"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie-detail"),
    path("movies/<int:pk>/update/", MovieUpdateView.as_view(), name="movie-update"),
    path("movies/<int:pk>/delete/", MovieDeleteView.as_view(), name="movie-delete"),
    # endregion

    # region ---------- Game Views  ----------
    path("games/", GameListView.as_view(), name="game-list"),
    path("games/create/", GameCreateView.as_view(), name="game-create"),
    path("games/<int:pk>/", GameDetailView.as_view(), name="game-detail"),
    path("games/<int:pk>/update/", GameUpdateView.as_view(), name="game-update"),
    path("games/<int:pk>/delete/", GameDeleteView.as_view(), name="game-delete"),
    # endregion

    # region ---------- Game Views  ----------
    path("events/", EventListView.as_view(), name="event-list"),
    path("events/create/", EventCreateView.as_view(), name="event-create"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event-detail"),
    path("events/<int:pk>/update/", EventUpdateView.as_view(), name="event-update"),
    path("events/<int:pk>/delete/", EventDeleteView.as_view(), name="event-delete"),
    # endregion

    # region ---------- Idea Views  ----------
    path("ideas/", IdeaListView.as_view(), name="idea-list"),
    path("ideas/create/", IdeaCreateView.as_view(), name="idea-create"),
    path("ideas/<int:pk>/", IdeaDetailView.as_view(), name="idea-detail"),
    path("ideas/<int:pk>/update/", IdeaUpdateView.as_view(), name="idea-update"),
    path("ideas/<int:pk>/delete/", IdeaDeleteView.as_view(), name="idea-delete"),
    # idea

    # region ---------- Desire Views  ----------
    path("desires/", DesireListView.as_view(), name="desire-list"),
    path("desires/create/", DesireCreateView.as_view(), name="desire-create"),
    path("desires/<int:pk>/", DesireDetailView.as_view(), name="desire-detail"),
    path("desires/<int:pk>/update/", DesireUpdateView.as_view(), name="desire-update"),
    path("desires/<int:pk>/delete/", DesireDeleteView.as_view(), name="desire-delete"),
    path('<str:model_name>/<int:id>/update-status/', update_status, name='update-status'),
    # idea
]

backend/lists/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class StatusChoices(models.TextChoices):
    PENDING = "pending", "Pending"
    ACTIVE = "active", "Active"
    COMPLETED = "completed", "Completed"


# CRUD +
class Movie(models.Model):
    name = models.CharField(
        max_length=255
    )
    description = models.TextField(
        blank=True,
        null=True
    )
    rate = models.IntegerField(
        null=True,
        blank=True,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5)
        ]
    )
    status = models.BooleanField(default=False)
    link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name


# CRUD +
class Game(models.Model):
    KOOP_CHOICES = [
        ('solo', 'Solo'),
        ('double', 'Double'),
        ('team', 'Team'),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField(
        blank=True,
        null=True
    )
    status = models.BooleanField(default=False)
    rate = models.IntegerField(
        null=True,
        blank=True,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5)
        ]
    )
    review = models.TextField(
        blank=True,
        null=True
    )
    coop = models.CharField(
        max_length=20,
        choices=KOOP_CHOICES,
        default='Solo',
    )

    def __str__(self):
        return self.name


# CRUD +
class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    date = models.DateField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.name


# CRUD +
class Idea(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.name


# CRUD +
class Desire(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    status = models.BooleanField(default=False)
    price = models.FloatField(blank=True, null=True)
    link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name


# CRUD -
class Goal(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.name


# CRUD -
class SubTask(models.Model):
    name = models.CharField(max_length=255)
    status = models.BooleanField(default=False)
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)

    def __str__(self):
        return f"[{self.goal.id}] {self.name}"

backend/lists/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from lists.models import Event


class NameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = "__all__"
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

backend/lists/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from lists.forms import NameSearchForm, EventForm
from lists.mixins import SearchFormMixin, NameSearchMixin
from lists.models import Movie, Game, Event, Idea, Desire


def index(request):
    return render(request, "index.html")


# region ---------- Movie Views  ----------
class MovieListView(
    SearchFormMixin,
    NameSearchMixin,
    generic.ListView,
):
    model = Movie
    context_object_name = "movie_list"
    template_name = "lists/movie/movie_list.html"
    paginate_by = 10


class MovieCreateView(generic.CreateView):
    model = Movie
    fields = "__all__"
    success_url = reverse_lazy("lists:movie-list")
    template_name = "lists/movie/movie_form.html"


class MovieDetailView(generic.DetailView):
    model = Movie
    template_name = "lists/movie/movie_detail.html"


class MovieUpdateView(generic.UpdateView):
    model = Movie
    fields = "__all__"
    success_url = reverse_lazy("lists:movie-list")
    template_name = "lists/movie/movie_form.html"


class MovieDeleteView(generic.DeleteView):
    model = Movie
    success_url = reverse_lazy("lists:movie-list")
    template_name = "lists/movie/movie_confirm_delete.html"


# endregion


# region ---------- Game Views  ----------
class GameListView(generic.ListView):
    model = Game
    context_object_name = "game_list"
    template_name = "lists/game/game_list.html"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameListView, self).get_context_data(**kwargs)

        sort_by = self.request.GET.get("sort", "status_priority")
        context["sort_by"] = sort_by

        name = self.request.GET.get("name", "")
        context["search_form"] = NameSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Game.objects.all()

        form = NameSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])

        sort_by = self.request.GET.get("sort", "status")

        valid_sort_fields = ["status", "name", "id", "coop"]
        if sort_by in valid_sort_fields:
            queryset = queryset.order_by(sort_by)

        return queryset


class GameCreateView(generic.CreateView):
    model = Game
    fields = "__all__"
    success_url = reverse_lazy("lists:game-list")
    template_name = "lists/game/game_form.html"


class GameDetailView(generic.DetailView):
    model = Game
    template_name = "lists/game/game_detail.html"


class GameUpdateView(generic.UpdateView):
    model = Game
    fields = "__all__"
    success_url = reverse_lazy("lists:game-list")
    template_name = "lists/game/game_form.html"


class GameDeleteView(generic.DeleteView):
    model = Game
    success_url = reverse_lazy("lists:game-list")
    template_name = "lists/game/game_confirm_delete.html"


# endregion


# region ---------- Event Views  ----------
class EventListView(
    SearchFormMixin,
    NameSearchMixin,
    generic.ListView
):
    model = Event
    context_object_name = "event_list"
    template_name = "lists/event/event_list.html"
    paginate_by = 10


class EventCreateView(generic.CreateView):
    model = Event
    form_class = EventForm
    success_url = reverse_lazy("lists:event-list")
    template_name = "lists/event/event_form.html"


class EventDetailView(generic.DetailView):
    model = Event
    template_name = "lists/event/event_detail.html"


class EventUpdateView(generic.UpdateView):
    model = Event
    fields = "__all__"
    success_url = reverse_lazy("lists:event-list")
    template_name = "lists/event/event_form.html"


class EventDeleteView(generic.DeleteView):
    model = Event
    success_url = reverse_lazy("lists:event-list")
    template_name = "lists/event/event_confirm_delete.html"


# endregion


# region ---------- Idea Views  ----------
class IdeaListView(
    SearchFormMixin,
    NameSearchMixin,
    generic.ListView
):
    model = Idea
    context_object_name = "idea_list"
    template_name = "lists/idea/idea_list.html"
    paginate_by = 10


class IdeaCreateView(generic.CreateView):
    model = Idea
    fields = "__all__"
    success_url = reverse_lazy("lists:idea-list")
    template_name = "lists/idea/idea_form.html"


class IdeaDetailView(generic.DetailView):
    model = Idea
    template_name = "lists/idea/idea_detail.html"


class IdeaUpdateView(generic.UpdateView):
    model = Idea
    fields = "__all__"
    success_url = reverse_lazy("lists:idea-list")
    template_name = "lists/idea/idea_form.html"


class IdeaDeleteView(generic.DeleteView):
    model = Idea
    success_url = reverse_lazy("lists:idea-list")
    template_name = "lists/idea/idea_confirm_delete.html"
# endregion


# region ---------- Desire Views  ----------
class DesireListView(
    SearchFormMixin,
    NameSearchMixin,
    generic.ListView
):
    model = Desire
    context_object_name = "desire_list"
    template_name = "lists/desire/desire_list.html"
    paginate_by = 10


class DesireCreateView(generic.CreateView):
    model = Desire
    fields = "__all__"
    success_url = reverse_lazy("lists:desire-list")
    template_name = "lists/desire/desire_form.html"


class DesireDetailView(generic.DetailView):
    model = Desire
    template_name = "lists/desire/desire_detail.html"


class DesireUpdateView(generic.UpdateView):
    model = Desire
    fields = "__all__"
    success_url = reverse_lazy("lists:desire-list")
    template_name = "lists/desire/desire_form.html"


class DesireDeleteView(generic.DeleteView):
    model = Desire
    success_url = reverse_lazy("lists:desire-list")
    template_name = "lists/desire/desire_confirm_delete.html"

# endregion


@csrf_exempt
def update_status(request, model_name, id):
    if request.method == 'POST':
        try:
            model = {
                'desire': Desire,
                'movie': Movie,
                'game': Game,
                'event': Event,
                'idea': Idea,
            }.get(model_name.lower())

            if not model:
                return JsonResponse({'success': False, 'error': 'Invalid model name'})

            instance = model.objects.get(id=id)
            data = json.loads(request.body)

            new_status = data.get('status') == 'true'
            instance.status = new_status
            instance.save()

            return JsonResponse({'success': True})
        except model.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Object not found'})
        except json.JSONDecodeError:
            return JsonResponse({'success': False, 'error': 'Invalid JSON'})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

backend/templates/lists/desire/desire_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Desire '{{ movie.name }}'?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

backend/templates/lists/desire/desire_detail.html
{% block content %}
  <h1>
    <a href="{% url 'lists:desire-delete' pk=desire.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
    <a href="{% url 'lists:desire-update' pk=desire.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <h4>
    Name: {{ desire.name }}
    {% if desire.link %}
      <a target="_blank" href="{{ desire.link }}">🔗</a>
    {% else %}
    {% endif %}
  </h4>
  <h4>
    {% if desire.price %}
      Price: {{ desire.price }} €
    {% else %}
    {% endif %}
  </h4>
  <h4>
    {% if desire.status %}
      Status: ✔️
    {% else %}
      Status: 🛒
    {% endif %}
  </h4>
  <hr>
  <h4>Description:</h4>
  <p class="lead">
    {{ desire.description }}
  </p>
{% endblock %}

backend/templates/lists/desire/desire_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} desire</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary mt-1 mb-3">
    <a href="{% url 'lists:desire-list' %}">
      <button type="button" value="Return" class="btn btn-secondary mt-1 mb-3">Return</button>
    </a>
  </form>
{% endblock %}

backend/templates/lists/desire/desire_list.html
{% extends "base.html" %}
{% load custom_filters %}
{% load static %}

{% block title %} Tables {% endblock %}

{% block content %}

  <div class="py-3">
    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">Desire list</h1>
      </div>
      <div>
        <a href="{% url 'lists:desire-create' %}" class="btn btn-primary link-to-page">
          Create
        </a>
      </div>
    </div>
  </div>

  {% include "includes/search_form.html" %}

  <div class="card border-0 shadow mb-4">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
          <thead class="thead-light">
          <tr>
            <th class="border-0 rounded-start">Name</th>
            <th class="border-0">Description</th>
            <th class="border-0">Price</th>
            <th class="border-0 rounded-end">Link</th>
          </tr>
          </thead>
          <tbody>
          {% for desire in desire_list %}
            <tr>

              <td class="td-nowrap">
                <div class="d-flex align-items-center">
                  <button
                      class="status-btn border-0 bg-transparent"
                      data-model="desire"
                      data-id="{{ desire.id }}"
                      data-status="{{ desire.status }}"
                  >
                    {% if desire.status %}
                      <span class="circle filled"></span>
                    {% else %}
                      <span class="circle"></span>
                    {% endif %}
                  </button>
                  <span
                      data-url="{% url 'lists:desire-detail' desire.id %}"
                      class="open-modal ml-2">
                        {{ desire.name }}
                  </span>
                </div>
              </td>

              <td class="td-break open-modal" data-url="{% url 'lists:desire-detail' desire.id %}">
                {{ desire.description }}
              </td>

              <td class="td-nowrap open-modal" data-url="{% url 'lists:desire-detail' desire.id %}">
                {% if desire.price %}
                  {{ desire.price }} €
                {% else %}
                  ——
                {% endif %}
              </td>

              <td class="td-nowrap">
                {% if desire.link %}
                  <a target="_blank" href="{{ desire.link }}">🔗</a>
                {% else %}
                  ——
                {% endif %}
              </td>

            </tr>
          {% endfor %}

          <div id="modal" class="modal" style="display: none;">
            <div class="modal-content">
              <span class="close-modal">&times;</span>
              <div id="modal-body"></div>
            </div>
          </div>

          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock content %}

{% block javascripts %}
  <script src="{% static 'assets/js/button_status_toggle.js' %}"></script>
  <script src="{% static 'assets/js/modal_handler.js' %}"></script>
{% endblock javascripts %}